{% set version = '0.1.7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-parglm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/parglm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/parglm/parglm_{{ version }}.tar.gz
  sha256: c3371a5e75df88b37b031ae8f73ccc693835469e6d66dc0a43fd68f0e4d57686

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib("c") }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
  run:
    - {{ native }}libwinpthread-git  # [win]
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo

test:
  commands:
    - $R -e "library('parglm')"           # [not win]
    - "\"%R%\" -e \"library('parglm')\""  # [win]

about:
  home: https://github.com/boennecd/parglm
  license: GPL-2.0-only
  summary: Provides a parallel estimation method for generalized linear models without compiling
    with a multithreaded LAPACK or BLAS.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
